language: go

go:
  - master

script:
  - ./run_test.sh

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      secure: "jCbG/MhM7odiPdYjjKOPWncVgT4htW7TzE75/tjJ5oQAX+SXFUoE/xgPhlWtqC6/bKWZ78SbHN93Z6k+js6IqJM32+J9MBFIaymsmuePeoE0EbqnnQT//bOwDDNrpVR1/EviQ5I4xeAWY+8ZfUwlDHP8X96IM1fOLR2rpK2tBWqgaUaToxZG7biwPI2TmrmP0jPRS9cWSYO4dH29R4ZRrMs6zFQ4Ql3kEiCrw45XsSxSdVY38NjLPtguxleATiXBPdj7T4Kxuef1FrGWOAtVu1nq0ahNDUiAbBMOi+IMfaiRfoAiv3Po5DNpzdccclzsjv/C8Rmy1/qgx2A6ZFK/JcLur+RD2hx1kl2WuAf/yyfmNscQcJWOj4NgnM/pvXCQy0BvvLN1ulCbcw4al1SFDu0nO99XirwgZ/KgOZQUurATnVkLbn71m6t/Y5Yql+pbeA2Yf8LCBhLR4qVAXz0tl9AFqpHSXv8HmVqUrPO9Lor8rl3oxZ5+gvc5ETchHVXqPh86u/frEpColI9KolLNFEFFBuJoa70VQgXpUm+06o2k0VYiyotgKpJ1alaqxYHXdd+ALTBT32iRn4wdx/FGTw6sOMzhBMOq69rfxava4/0rKCWY1LJRVgknS8Hkfvb7gp1CFPFbs/D3MBeJdEgsrEKVYuT8czcdTpwZ3Gwb/oE="
    on_success: change
    on_failure: always
